import { TokenType } from '../Lexer/TokenType';

export type Terminal = TokenType;

export enum ENonTerminal {
  START = 2000,
  translation_unit,
  variable_identifier,
  variable_identifier_node,
  primary_expression,
  postfix_expression,
  integer_expression,
  function_call,
  function_call_generic,
  function_call_header_no_parameters,
  function_call_header_with_parameters,
  function_call_header,
  function_identifier,
  constructor_identifier,
  unary_expression,
  unary_operator,
  multiplicative_expression,
  additive_expression,
  shift_expression,
  relational_expression,
  equality_expression,
  and_expression,
  inclusive_or_expression,
  logical_and_expression,
  logical_xor_expression,
  logical_or_expression,
  conditional_expression,
  assignment_expression,
  assignment_operator,
  expression,
  constant_expression,
  declaration,
  function_prototype,
  function_declarator,
  function_header_with_parameters,
  function_header,
  parameter_declarator,
  parameter_declaration,
  parameter_qualifier,
  parameter_type_specifier,
  init_declarator_list,
  single_declaration,
  fully_specified_type,
  type_qualifier,
  type_specifier,
  type_specifier_no_prec,
  basic_type,
  struct_specifier,
  struct_declaration_list,
  struct_declaration,
  struct_declarator_list,
  struct_declarator,
  precision_qualifier,
  initializer,
  declaration_statement,
  statement_no_new_scope,
  simple_statement,
  compound_statement_with_scope,
  statement_with_scope,
  compound_statement_no_new_scope,
  statement_list,
  iteration_statement_no_new_scope,
  expression_statement,
  selection_statement,
  selection_rest_statement,
  condition,
  iteration_statement,
  for_init_statement,
  for_rest_statement,
  jump_statement,
  external_declaration,
  function_definition,
  field_selection,
  bool_constant,
  function_identifier_node,
  typename_identifier_node,

  // TEST:
  E,
  T,
  X,
  Y,
  S,
  A,
  F,
  C,
  B,
  D,
  G,
  L,
  R,
  exp,
  term,
  factor,
  program,
  statements,
  assignment,
  block,
  type,
  ifStmt,
  elsePart,
  init,
  relOp,
  logicExp,
  // TEST: end
}

export type GrammarSymbol = Terminal | ENonTerminal;

export type Derivation = GrammarSymbol[];
